# Generated by Django 5.0.3 on 2024-03-28 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0003_repaired_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overdue',
            options={'verbose_name_plural': 'Overdue'},
        ),
        migrations.RenameField(
            model_name='repaired',
            old_name='request',
            new_name='requests',
        ),
    ]
