# Generated by Django 5.0.3 on 2024-03-28 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0004_alter_overdue_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overdue',
            name='requests',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='MyApp1.requests'),
            preserve_default=False,
        ),
    ]
