# Generated by Django 5.0.3 on 2024-03-29 01:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0007_maintenance_overdue_requests_repaired_requests'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Maintenance',
        ),
        migrations.AlterField(
            model_name='overdue',
            name='assetid',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='repaired',
            name='assetid',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='requests',
            name='assetid',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]+$')]),
        ),
    ]
